<<<<<<< HEAD
[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.14.0",
    "faiss-cpu>=1.9.0.post1",
    "fastapi>=0.115.5",
    "google-generativeai>=0.8.3",
    "langchain-ollama>=0.2.0",
    "langdetect>=1.0.9",
    "openai>=1.55.0",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.1",
]
=======
[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.5",
    "openai>=1.55.0",
    "uvicorn>=0.32.1",
]
>>>>>>> ecb15eb (ui amazing)
